CREATE TABLE "Blog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "posts" JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE "MediaArchive" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "items" JSONB NOT NULL DEFAULT '[]'
);
